In [1]:
import numpy as np

In [3]:
pip install numpy

In [7]:
import numpy as np
array_1 = np.array([4,5,7,10])
array_2=np.array([7,10])
print(array_2)
np.mean(array_2)

[ 7 10]


np.float64(8.5)

In [ ]:
#Compute and display the mean of array_1 and the overall mean of array_2.


In [2]:
a=np.array([4,5,7,10])
print (a)

[ 4  5  7 10]


In [3]:
#Print the type of the variable to verify that it is a numpy.ndarray.
type(a)

numpy.ndarray

In [ ]:
from inspect import signature

In [ ]:
#scaler
s=5
s

5

In [ ]:
#vectors (2d dimension)
v=np.array([5,-2,4])
v

array([ 5, -2,  4])

In [ ]:
#matrix
m=np.array([[5,12,6],[-3,0,14]])
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
#data types
type(v),type(m),type(s)

(numpy.ndarray, numpy.ndarray, int)

In [ ]:
#data shapes
v.shape


(3,)

In [ ]:
m.shape

(2, 3)

In [ ]:
#creating a column vector (reshape gives an array a new shape, without changing its data)
v.reshape(1,3)


array([[ 5, -2,  4]])

In [ ]:
m.reshape(3,2)

array([[ 5, 12],
       [ 6, -3],
       [ 0, 14]])

In [ ]:
#Tensor
m1=np.array([[22,5,7,13],[14,2,10,6],[12,7,3,16]])
m1

array([[22,  5,  7, 13],
       [14,  2, 10,  6],
       [12,  7,  3, 16]])

In [ ]:
m1.shape

(3, 4)

In [ ]:
m2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m2.shape

(3, 4)

In [ ]:
#creating array
t=np.array([m1,m2])
t

array([[[22,  5,  7, 13],
        [14,  2, 10,  6],
        [12,  7,  3, 16]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
t.shape

(2, 3, 4)

In [ ]:
#addition notes: for this array size should be same.
m1+m2

array([[23,  7, 10, 17],
       [19,  8, 17, 14],
       [21, 17, 14, 28]])

In [ ]:
#substruction
m1-m2

array([[21,  3,  4,  9],
       [ 9, -4,  3, -2],
       [ 3, -3, -8,  4]])

In [ ]:
#adding vectors together
v1=np.array([1,2,3,4,5])
v2=np.array([5,4,3,2,1])

In [ ]:
v1+v2

array([6, 6, 6, 6, 6])

In [ ]:
v1-v2

array([-4, -2,  0,  2,  4])

In [ ]:
#transposing matrics
A=np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [ ]:
B=np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [ ]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [ ]:
#transposing vectors
x=np.array([1,2,3])
x


array([1, 2, 3])

In [ ]:
x.T # In python 1d arrays don't really get transposed(in the memory of the computer)

array([1, 2, 3])

In [ ]:
x.shape

(3,)

In [ ]:
x_reshaped=x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [ ]:
x_reshaped.T

array([[1],
       [2],
       [3]])

In [ ]:
#dot product
x=np.array([2,8,-4])
y=np.array([1,-7,3])
np.dot(x,y)

np.int64(-66)

In [ ]:
np.dot(x,y)

np.int64(-66)

In [ ]:
#scaler multiply by vector
x

array([ 2,  8, -4])

In [ ]:
np.dot(x,5) #we get a vector with the same lenghth

array([ 10,  40, -20])

In [ ]:
#scaler*scaler
np.dot(5,6)


np.int64(30)

In [ ]:
#scaler*matrics
A=np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [ ]:
A*3 #shape of the matrix doesn't change

array([[15, 36, 18],
       [-9,  0, 42]])

In [2]:
import numpy as np

In [8]:
# Compute and display the mean of array_1 and the overall mean of array_2.
print("Mean of array_1:", np.mean(array_1))
print("Overall mean of array_2:", np.mean(array_2))

Mean of array_1: 6.5
Overall mean of array_2: 8.5


In [ ]:
#Compute and display the row-wise mean of array_2.Compute and display the column-wise mean of array_2

In [9]:
# array_2 is a 1-dimensional array, so we compute the overall mean.
print("Overall mean of array_2:", np.mean(array_2))

Overall mean of array_2: 8.5


In [11]:
import numpy as np
array_1 = np.array([4,5,7,10])
array_2=np.array([[4,5],[7,10]])
print(array_2)
print(np.mean(array_1))
print(np.mean(array_2))
#row wise mean of array_2
print(np.mean(array_2,axis=1))
#column wise mean of array_2
print(np.mean(array_2,axis=0))

[[ 4  5]
 [ 7 10]]
6.5
6.5
[4.5 8.5]
[5.5 7.5]


In [12]:
#Compute the column-wise mean and cast the result to integer
print(np.mean(array_2, axis = 0, dtype=int))

[5 7]
